Repository OCA/server-backend, pull requests merged in 2020-12, with the labels that each got.

#102 [IMP] base_global_discount: add specific security group
  base_global_discount/__manifest__.py
  base_global_discount/migrations/12.0.2.0.0/post_migrate.py
  base_global_discount/models/res_partner.py
  base_global_discount/readme/CONFIGURE.rst
  base_global_discount/readme/USAGE.rst
  base_global_discount/security/ir.model.access.csv
  base_global_discount/security/security.xml
  base_global_discount/views/global_discount_views.xml
  base_global_discount/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#92 [13.0] base_user_role: Corrected a bug on the attribution of the 'User roles' default applic…
  base_user_role/models/role.py
Labels: approved, bot is merging ⏳, ready to merge

#103 [FIX][12.0] base_global_discount: prevent warning abount fields with same name
  base_global_discount/models/res_partner.py
  base_global_discount/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#106 [IMP] base_user_role: Adding a new tab for user comments in roles form.
  base_user_role/models/role.py
  base_user_role/readme/CONTRIBUTORS.rst
  base_user_role/views/role.xml
Labels: bot is merging ⏳

#107 [IMP] base_user_role: Adding a new tab for user comments in roles form.
  base_user_role/models/role.py
  base_user_role/readme/CONTRIBUTORS.rst
  base_user_role/views/role.xml
Labels: approved, bot is merging ⏳, ready to merge
