Repository OCA/server-backend, pull requests merged in 2021-04, with the labels that each got.

#121 [IMP] base_global_discount: add specific security group
  base_global_discount/README.rst
  base_global_discount/__manifest__.py
  base_global_discount/models/res_partner.py
  base_global_discount/readme/CONFIGURE.rst
  base_global_discount/readme/USAGE.rst
  base_global_discount/security/ir.model.access.csv
  base_global_discount/security/security.xml
  base_global_discount/views/global_discount_views.xml
  base_global_discount/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#122 [fix] requirements.txt: Pin pymssql to 2.1.5
  requirements.txt
Labels: approved

#114 [FIX] base_user_role : affect correct default category, when creating the related group
  base_user_role/__manifest__.py
  base_user_role/data/ir_module_category.xml
  base_user_role/migrations/12.0.2.1.0/post-migration.py
  base_user_role/models/role.py
  base_user_role/tests/test_user_role.py
Labels: approved, bot is merging ⏳, ready to merge

#120 [IMP] base_user_role : prevent errors if users are not accessible by ACL, when updating roles
  base_user_role/models/role.py
Labels: approved, bot is merging ⏳, ready to merge
