Repository OCA/server-backend, pull requests merged in 2021-01, with the labels that each got.

#60 [13.0][MIG] base_external_dbsource_mssql: Migration to v13.0
  base_external_dbsource_mssql/README.rst
  base_external_dbsource_mssql/__init__.py
  base_external_dbsource_mssql/__manifest__.py
  base_external_dbsource_mssql/demo/base_external_dbsource.xml
  base_external_dbsource_mssql/i18n/base_external_dbsource_mssql.pot
  base_external_dbsource_mssql/i18n/de.po
  base_external_dbsource_mssql/i18n/es.po
  base_external_dbsource_mssql/i18n/hr.po
  base_external_dbsource_mssql/i18n/nl_NL.po
  base_external_dbsource_mssql/i18n/pt_BR.po
  base_external_dbsource_mssql/i18n/sl.po
  base_external_dbsource_mssql/i18n/tr.po
  base_external_dbsource_mssql/models/__init__.py
  base_external_dbsource_mssql/models/base_external_dbsource.py
  base_external_dbsource_mssql/readme/CONFIGURE.rst
  base_external_dbsource_mssql/readme/CONTRIBUTORS.rst
  base_external_dbsource_mssql/readme/DESCRIPTION.rst
  base_external_dbsource_mssql/readme/INSTALL.rst
  base_external_dbsource_mssql/readme/ROADMAP.rst
  base_external_dbsource_mssql/readme/USAGE.rst
  base_external_dbsource_mssql/static/description/icon.png
  base_external_dbsource_mssql/static/description/index.html
  base_external_dbsource_mssql/tests/__init__.py
  base_external_dbsource_mssql/tests/test_base_external_dbsource.py
  setup/base_external_dbsource_mssql/odoo/addons/base_external_dbsource_mssql
  setup/base_external_dbsource_mssql/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#108 [FIX] base_user_role: remove multicompany functionality
  base_user_role/models/role.py
  base_user_role/models/user.py
  base_user_role/tests/test_user_role.py
  base_user_role/views/role.xml
  base_user_role/views/user.xml
Labels: approved, bot is merging ⏳

#109 [IMP] base_user_role: UX improvements
  base_user_role/models/role.py
  base_user_role/readme/CONTRIBUTORS.rst
  base_user_role/views/user.xml
Labels: bot is merging ⏳
