Repository OCA/server-backend, pull requests merged in 2022-08, with the labels that each got.

#148 [15.0][MIG] base_global_discount
  base_global_discount/README.rst
  base_global_discount/__init__.py
  base_global_discount/__manifest__.py
  base_global_discount/i18n/base_global_discount.pot
  base_global_discount/i18n/es.po
  base_global_discount/i18n/nl_NL.po
  base_global_discount/i18n/pt.po
  base_global_discount/models/__init__.py
  base_global_discount/models/global_discount.py
  base_global_discount/models/res_partner.py
  base_global_discount/readme/CONFIGURE.rst
  base_global_discount/readme/CONTRIBUTORS.rst
  base_global_discount/readme/DESCRIPTION.rst
  base_global_discount/readme/USAGE.rst
  base_global_discount/security/ir.model.access.csv
  base_global_discount/security/security.xml
  base_global_discount/static/description/icon.png
  base_global_discount/static/description/index.html
  base_global_discount/tests/__init__.py
  base_global_discount/tests/test_global_discount.py
  base_global_discount/views/global_discount_views.xml
  base_global_discount/views/res_partner_views.xml
  base_user_role/tests/test_user_role.py
  setup/base_global_discount/odoo/addons/base_global_discount
  setup/base_global_discount/setup.py
Labels: approved, bot is merging ⏳, stale

#167 [13.0][FIX]base_user_role: Show active users on Users page
  base_user_role/models/role.py
  base_user_role/models/user.py
Labels: approved, ready to merge, bot is merging ⏳

#168 [15.0] FIX: `base_user_role` sudo
  base_user_role/models/role.py
  base_user_role/tests/test_user_role.py
Labels: bug, bot is merging ⏳

#152 [14.0][FW][FIX] base_import_match: "Unable to use a closed cursor"
  base_import_match/models/base_import.py
Labels: bot is merging ⏳

#163 [ADD] pglogical
  pglogical/README.rst
  pglogical/__init__.py
  pglogical/__manifest__.py
  pglogical/hooks.py
  pglogical/readme/CONFIGURE.rst
  pglogical/readme/CONTRIBUTORS.rst
  pglogical/readme/DESCRIPTION.rst
  pglogical/readme/USAGE.rst
  pglogical/static/description/icon.png
  pglogical/static/description/index.html
  pglogical/tests/__init__.py
  pglogical/tests/test_pglogical.py
  requirements.txt
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#176 [14.0][FW] base_user_role: multiple ports from 13.0
  base_user_role/models/role.py
  base_user_role/models/user.py
Labels: approved, migration, bot is merging ⏳

#177 [15.0][FW] base_user_role: multiple ports from 14.0
  base_user_role/models/role.py
  base_user_role/models/user.py
Labels: migration, bot is merging ⏳

#171 [15.0][FIX] UserWarning: Field res.groups.trans_parent_ids should be …
  base_user_role/models/res_groups.py
Labels: bug, bot is merging ⏳

#179 [FIX][14.0]Dependencies in view
  server_action_navigate/__manifest__.py
Labels: bot is merging ⏳

#165 [IMP] base_global_discount: Add discounted amount selection
  base_global_discount/__manifest__.py
  base_global_discount/models/global_discount.py
  base_global_discount/readme/CONTRIBUTORS.rst
  base_global_discount/views/global_discount_views.xml
Labels: approved, ready to merge, bot is merging ⏳
