Repository OCA/server-backend, pull requests merged in 2022-10, with the labels that each got.

#178 [FIX][12.0] pglogical: don't replicate aggregate functions
  pglogical/hooks.py
Labels: approved, ready to merge, bot is merging ⏳

#189 [15.0][FW] [14.0][FW][FIX] base_import_match: "Unable to use a closed cursor"
  base_import_match/models/base_import.py
Labels: bug, needs review, bot is merging ⏳

#191 [16.0][FW] [15.0][FW] [IMP][14.0] Module: base_user_role show rules and access
  base_user_role/models/role.py
  base_user_role/views/role.xml
Labels: bot is merging ⏳

#190 [DOC] base_user_role: set development status to 'Production/Stable'
  base_user_role/__manifest__.py
Labels: bot is merging ⏳

#193 [15.0][FW] [DOC] base_user_role: set development status to 'Production/Stable'
  base_user_role/__manifest__.py
Labels: bot is merging ⏳

#194 [16.0][FW] [DOC] base_user_role: set development status to 'Production/Stable'
  base_user_role/__manifest__.py
Labels: bot is merging ⏳

#181 [15.0][FW] [14.0][FW] [13.0][FIX] base_user_role: Improve tests resiliency
  base_user_role/tests/test_user_role.py
Labels: bot is merging ⏳
