Repository OCA/server-backend, pull requests merged in 2022-11, with the labels that each got.

#188 [14.0][FIX] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  base_external_dbsource/tests/test_base_external_dbsource.py
Labels: approved, ready to merge, bot is merging ⏳

#195 12.0 - [REF] requirements.txt: Use "pymssql<=2.2.5" to fix "Failed building wheel for pymssql"
  requirements.txt
  setup/base_external_dbsource_mssql/setup.py
Labels: needs review

#198 [16.0][FIX] Update from copier template
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#199 [15.0][MIG] base_external_dbsource_sqlite: Migration to 15.0
  base_external_dbsource_sqlite/README.rst
  base_external_dbsource_sqlite/__init__.py
  base_external_dbsource_sqlite/__manifest__.py
  base_external_dbsource_sqlite/demo/base_external_dbsource.xml
  base_external_dbsource_sqlite/i18n/base_external_dbsource_sqlite.pot
  base_external_dbsource_sqlite/i18n/de.po
  base_external_dbsource_sqlite/i18n/es.po
  base_external_dbsource_sqlite/i18n/hr.po
  base_external_dbsource_sqlite/i18n/nl_NL.po
  base_external_dbsource_sqlite/i18n/pt_BR.po
  base_external_dbsource_sqlite/i18n/sl.po
  base_external_dbsource_sqlite/i18n/tr.po
  base_external_dbsource_sqlite/models/__init__.py
  base_external_dbsource_sqlite/models/base_external_dbsource.py
  base_external_dbsource_sqlite/readme/CONFIGURE.rst
  base_external_dbsource_sqlite/readme/CONTRIBUTORS.rst
  base_external_dbsource_sqlite/readme/DESCRIPTION.rst
  base_external_dbsource_sqlite/readme/INSTALL.rst
  base_external_dbsource_sqlite/readme/ROADMAP.rst
  base_external_dbsource_sqlite/readme/USAGE.rst
  base_external_dbsource_sqlite/static/description/icon.png
  base_external_dbsource_sqlite/static/description/index.html
  base_external_dbsource_sqlite/tests/__init__.py
  base_external_dbsource_sqlite/tests/test_base_external_dbsource.py
  requirements.txt
  setup/base_external_dbsource_sqlite/odoo/addons/base_external_dbsource_sqlite
  setup/base_external_dbsource_sqlite/setup.py
Labels: approved, bot is merging ⏳

#172 [15.0][MIG] base_external_system: Migration to 15.0
  base_external_system/README.rst
  base_external_system/__init__.py
  base_external_system/__manifest__.py
  base_external_system/demo/external_system_os_demo.xml
  base_external_system/i18n/base_external_system.pot
  base_external_system/models/__init__.py
  base_external_system/models/external_system.py
  base_external_system/models/external_system_adapter.py
  base_external_system/models/external_system_os.py
  base_external_system/readme/CONFIGURE.rst
  base_external_system/readme/CONTRIBUTORS.rst
  base_external_system/readme/DESCRIPTION.rst
  base_external_system/readme/USAGE.rst
  base_external_system/security/ir.model.access.csv
  base_external_system/static/description/icon.png
  base_external_system/static/description/index.html
  base_external_system/tests/__init__.py
  base_external_system/tests/common.py
  base_external_system/tests/test_external_system.py
  base_external_system/tests/test_external_system_adapter.py
  base_external_system/tests/test_external_system_os.py
  base_external_system/views/external_system_view.xml
  setup/base_external_system/odoo/addons/base_external_system
  setup/base_external_system/setup.py
Labels: bot is merging ⏳, stale
