Repository OCA/server-backend, pull requests merged in 2022-09, with the labels that each got.

#182 [14.0][FW] [15.0] FIX: `base_user_role` sudo
  base_user_role/models/role.py
  base_user_role/tests/test_user_role.py
Labels: bug, bot is merging ⏳

#169 [IMP][14.0] Module: base_user_role show rules and access
  base_user_role/models/group.py
  base_user_role/models/role.py
  base_user_role/views/role.xml
Labels: needs review, bot is merging ⏳

#183 [15.0][FW] [IMP][14.0] Module: base_user_role show rules and access
  base_user_role/models/role.py
  base_user_role/views/role.xml
Labels: bot is merging ⏳
