Repository OCA/server-backend, pull requests merged in 2023-07, with the labels that each got.

#192 [15.0][ADD] base_external_dbsource_sap_hana: New module to connect to SAP Hana using Alchemy
  base_external_dbsource_sap_hana/README.rst
  base_external_dbsource_sap_hana/__init__.py
  base_external_dbsource_sap_hana/__manifest__.py
  base_external_dbsource_sap_hana/demo/base_external_dbsource.xml
  base_external_dbsource_sap_hana/models/__init__.py
  base_external_dbsource_sap_hana/models/base_external_dbsource.py
  base_external_dbsource_sap_hana/readme/CONFIGURE.rst
  base_external_dbsource_sap_hana/readme/CONTRIBUTORS.rst
  base_external_dbsource_sap_hana/readme/DESCRIPTION.rst
  base_external_dbsource_sap_hana/readme/INSTALL.rst
  base_external_dbsource_sap_hana/readme/USAGE.rst
  base_external_dbsource_sap_hana/static/description/icon.png
  base_external_dbsource_sap_hana/static/description/index.html
  base_external_dbsource_sap_hana/tests/__init__.py
  base_external_dbsource_sap_hana/tests/test_base_external_dbsource_sap_hana.py
  requirements.txt
  setup/base_external_dbsource_sap_hana/odoo/addons/base_external_dbsource_sap_hana
  setup/base_external_dbsource_sap_hana/setup.py
Labels: bot is merging ⏳, stale

#224 [13.0][FIX] base_user_role: filter domain for user role search
  .pre-commit-config.yaml
  base_external_dbsource/models/base_external_dbsource.py
  base_external_dbsource/tests/test_base_external_dbsource.py
  base_external_dbsource_mssql/models/base_external_dbsource.py
  base_external_dbsource_mssql/tests/test_base_external_dbsource.py
  base_external_dbsource_mysql/models/base_external_dbsource.py
  base_external_dbsource_mysql/tests/test_base_external_dbsource.py
  base_external_dbsource_sqlite/models/base_external_dbsource.py
  base_external_dbsource_sqlite/tests/test_base_external_dbsource.py
  base_external_system/models/external_system.py
  base_external_system/tests/test_external_system.py
  base_global_discount/models/global_discount.py
  base_import_match/models/base.py
  base_import_match/models/base_import.py
  base_import_match/tests/test_import.py
  base_user_role/models/role.py
  base_user_role/views/user.xml
  server_action_navigate/models/ir_actions_server_navigate_line.py
Labels: approved, bot is merging ⏳

#227 [14.0][FW][FIX] base_user_role: filter domain for user role search
  base_user_role/views/user.xml
Labels: bot is merging ⏳

#228 [15.0][FW][FIX] base_user_role: filter domain for user role search
  base_user_role/views/user.xml
Labels: approved, bot is merging ⏳

#229 [16.0][FW][FIX] base_user_role: filter domain for user role search
  base_user_role/views/user.xml
Labels: approved, bot is merging ⏳

#230 [12.0][IMP] update repository template
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  base_external_dbsource/tests/test_base_external_dbsource.py
  base_external_dbsource_mssql/readme/ROADMAP.rst
  base_external_dbsource_mysql/readme/CONFIGURE.rst
  base_external_dbsource_sqlite/__manifest__.py
  base_import_match/__manifest__.py
  base_suspend_security/__manifest__.py
  base_user_role/readme/CONFIGURE.rst
  base_user_role_history/__manifest__.py
  requirements.txt
  server_action_navigate/__manifest__.py
  server_action_navigate/i18n/fr.po
Labels: approved, bot is merging ⏳

#214 [ADD] base_portal_type
  base_portal_type/README.rst
  base_portal_type/__init__.py
  base_portal_type/__manifest__.py
  base_portal_type/data/ir_module_category.xml
  base_portal_type/demo/res_groups.xml
  base_portal_type/models/__init__.py
  base_portal_type/models/res_groups.py
  base_portal_type/readme/CONTRIBUTORS.rst
  base_portal_type/readme/DESCRIPTION.rst
  base_portal_type/readme/ROADMAP.rst
  base_portal_type/readme/USAGE.rst
  base_portal_type/static/description/icon.png
  base_portal_type/static/description/index.html
  base_portal_type/tests/__init__.py
  base_portal_type/tests/test_base_portal_type.py
  setup/base_portal_type/odoo/addons/base_portal_type
  setup/base_portal_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳
