Repository OCA/server-backend, pull requests merged in 2024-05, with the labels that each got.

#288 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  base_user_role_company/models/role.py
Labels: help wanted, needs review, bot is merging ⏳

#286 [ADD][15.0] base_ical: Module to expose iCalendar over URL
  base_ical/README.rst
  base_ical/__init__.py
  base_ical/__manifest__.py
  base_ical/controllers/__init__.py
  base_ical/controllers/main.py
  base_ical/demo/base_ical.xml
  base_ical/i18n/.empty
  base_ical/models/__init__.py
  base_ical/models/base_ical.py
  base_ical/models/base_ical_url_description.py
  base_ical/models/base_ical_url_show.py
  base_ical/models/res_users.py
  base_ical/readme/CONFIGURE.rst
  base_ical/readme/CONTRIBUTORS.rst
  base_ical/readme/DESCRIPTION.rst
  base_ical/readme/ROADMAP.rst
  base_ical/readme/USAGE.rst
  base_ical/security/ir.model.access.csv
  base_ical/static/description/icon.png
  base_ical/static/description/index.html
  base_ical/tests/__init__.py
  base_ical/tests/test_base_ical.py
  base_ical/views/base_ical.xml
  base_ical/views/res_users.xml
  requirements.txt
  setup/base_ical/odoo/addons/base_ical
  setup/base_ical/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#258 [16.0] mig server_action_navigate (from 14.0)
  server_action_navigate/README.rst
  server_action_navigate/__init__.py
  server_action_navigate/__manifest__.py
  server_action_navigate/demo/ir_actions_server.xml
  server_action_navigate/hooks.py
  server_action_navigate/i18n/fr.po
  server_action_navigate/i18n/it.po
  server_action_navigate/i18n/server_action_navigate.pot
  server_action_navigate/models/__init__.py
  server_action_navigate/models/ir_actions_server.py
  server_action_navigate/models/ir_actions_server_navigate_line.py
  server_action_navigate/readme/CONFIGURE.rst
  server_action_navigate/readme/CONTRIBUTORS.rst
  server_action_navigate/readme/DESCRIPTION.rst
  server_action_navigate/readme/USAGE.rst
  server_action_navigate/security/ir.model.access.csv
  server_action_navigate/static/description/icon.png
  server_action_navigate/static/description/index.html
  server_action_navigate/static/description/ir_actions_server_form.png
  server_action_navigate/static/description/res_partner_category_tree.png
  server_action_navigate/static/description/res_users_tree.png
  server_action_navigate/tests/__init__.py
  server_action_navigate/tests/test_module.py
  server_action_navigate/views/view_ir_actions_server.xml
  setup/server_action_navigate/odoo/addons/server_action_navigate
  setup/server_action_navigate/setup.py
Labels: bot is merging ⏳

#221 [16.0][IMP] base_global_discount: Add check global discount in product
  base_global_discount/__manifest__.py
  base_global_discount/models/__init__.py
  base_global_discount/models/product_product.py
  base_global_discount/models/product_template.py
  base_global_discount/views/product_views.xml
Labels: bot is merging ⏳
