Repository OCA/server-backend, pull requests merged in 2025-01, with the labels that each got.

#323 [FIX]base_external_dbsource_mssql: proper python versions for bookworm
  base_external_dbsource_mssql/__manifest__.py
  base_external_dbsource_mssql/static/description/index.html
  requirements.txt
Labels: approved, bot is merging ⏳

#326 [16.0][IMP] base_group_backend: allow read on calendar.event and remove Dashboard menu for backend users
  base_group_backend/README.rst
  base_group_backend/__manifest__.py
  base_group_backend/data/ir_ui_menu.xml
  base_group_backend/demo/backend_dummy_model.xml
  base_group_backend/models/__init__.py
  base_group_backend/models/ir_ui_menu.py
  base_group_backend/models/res_users.py
  base_group_backend/readme/CONFIGURE.rst
  base_group_backend/readme/DESCRIPTION.rst
  base_group_backend/readme/ROADMAP.rst
  base_group_backend/readme/USAGE.rst
  base_group_backend/security/ir.model.access.csv
  base_group_backend/static/description/index.html
  base_group_backend/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳

#335 [17.0][FW] base_user_role: multiple ports from 15.0
  .oca/oca-port/blacklist/base_user_role.json
  base_user_role/tests/test_user_role.py
Labels: bot is merging ⏳

#336 [16.0][FW] base_user_role: multiple ports from 15.0
  .oca/oca-port/blacklist/base_user_role.json
  base_user_role/tests/test_user_role.py
Labels: bot is merging ⏳

#337 [18.0][FW] [17.0][FW] base_user_role: multiple ports from 15.0
  base_user_role/tests/test_user_role.py
Labels: bot is merging ⏳
