Repository OCA/server-backend, pull requests merged in 2025-05, with the labels that each got.

#344 [MIG] server_action_navigate: Migration to 17.0
  server_action_navigate/README.rst
  server_action_navigate/__init__.py
  server_action_navigate/__manifest__.py
  server_action_navigate/demo/ir_actions_server.xml
  server_action_navigate/hooks.py
  server_action_navigate/i18n/fr.po
  server_action_navigate/i18n/it.po
  server_action_navigate/i18n/server_action_navigate.pot
  server_action_navigate/models/__init__.py
  server_action_navigate/models/ir_actions_server.py
  server_action_navigate/models/ir_actions_server_navigate_line.py
  server_action_navigate/pyproject.toml
  server_action_navigate/readme/CONFIGURE.md
  server_action_navigate/readme/CONTRIBUTORS.md
  server_action_navigate/readme/DESCRIPTION.md
  server_action_navigate/readme/USAGE.md
  server_action_navigate/security/ir.model.access.csv
  server_action_navigate/static/description/icon.png
  server_action_navigate/static/description/index.html
  server_action_navigate/static/description/ir_actions_server_form.png
  server_action_navigate/static/description/res_partner_category_tree.png
  server_action_navigate/static/description/res_users_tree.png
  server_action_navigate/tests/__init__.py
  server_action_navigate/tests/test_module.py
  server_action_navigate/views/view_ir_actions_server.xml
Labels: bot is merging ⏳

#340 [FIX] base_user_role_company: Do not auto install this module.
  base_user_role_company/__manifest__.py
  base_user_role_company/static/description/index.html
Labels: approved, bot is merging ⏳

#360 [FIX] base_user_role_company: Do not auto install this module.
  base_user_role_company/__manifest__.py
Labels: needs review, bot is merging ⏳

#324 [17.0][FIX] base_user_role_company: wrong arguments in new odoo releases
  base_user_role_company/controllers/main.py
Labels: bot is merging ⏳, stale

#347 [18.0][FIX] base_user_role_company: Roles are filtered so none which exceed date_to are used
  base_user_role_company/models/user.py
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_use_only_enabled_roles.py
Labels: approved, ready to merge, bot is merging ⏳

#361 [FIX][16.0]: base_user_role_company: Roles are filtered so none which exceed date_to are used
  base_user_role_company/models/user.py
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_use_only_enabled_roles.py
Labels: bot is merging ⏳

#319 [16.0][FIX] base_user_role: default roles
  base_user_role/models/user.py
  base_user_role/tests/test_user_role.py
Labels: approved, ready to merge, bot is merging ⏳

#325 [FIX] base_user_role_company: fix column_invisible
  base_user_role_company/views/role.xml
Labels: approved, ready to merge, bot is merging ⏳
